apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app-chart.fullname" . }}-prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    remote_write:
    - url: "http://192.168.1.76:9090/api/v1/write"  # Адрес Grafana или Prometheus на хосте

    scrape_configs:
      # Мониторинг Istio
      - job_name: 'istio'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['istio-system']
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_istio]
            action: keep
            regex: .+
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: keep
            regex: 'istio-proxy|istiod'

      # Мониторинг вашего приложения
      - job_name: 'my-app'
        static_configs:
          - targets: ['{{ include "my-app-chart.fullname" . }}:80']
