apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app-chart.fullname" . }}-prometheus
  labels:
    app.kubernetes.io/name: {{ include "my-app-chart.fullname" . }}
    helm.sh/chart: {{ include "my-app-chart.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "my-app-chart.fullname" . }}  # Должно совпадать с template.metadata.labels
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "my-app-chart.fullname" . }}  # Те же label, что и в selector
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      automountServiceAccountToken: false  # Перенесено в правильное место
      containers:
        - name: prometheus
          image: "prom/prometheus:v2.36.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: config
          configMap:
            name: {{ include "my-app-chart.fullname" . }}-prometheus-config
