apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-app-chart.fullname" . }}-secrets
stringData:
  FLUENT_BIT_PASSWORD: "{{ .Values.fluentBit.password }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-app-chart.fullname" . }}-registry-credentials
  labels:
    app.kubernetes.io/name: {{ include "my-app-chart.fullname" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.global.imageRegistry (.Values.imageCredentials.username | default "") (.Values.imageCredentials.password | default "") (printf "%s:%s" (.Values.imageCredentials.username | default "") (.Values.imageCredentials.password | default "") | b64enc) | b64enc }}
